# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main2.ui'
#
# Created: Wed Jul 05 16:48:09 2017
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar

from matplotlib.figure import Figure
import numpy as np

class Ui_Form(object):
    def setupUi(self, Form):
        self.form = Form
        Form.setObjectName("Form")
        Form.resize(750, 646)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(647, 640))
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnOpen = QtWidgets.QPushButton(Form)
        self.btnOpen.setMinimumSize(QtCore.QSize(90, 0))
        self.btnOpen.setObjectName("btnOpen")
        self.horizontalLayout.addWidget(self.btnOpen)
        self.btnRun = QtWidgets.QPushButton(Form)
        self.btnRun.setMinimumSize(QtCore.QSize(90, 0))
        self.btnRun.setObjectName("btnRun")
        self.horizontalLayout.addWidget(self.btnRun)
        self.btnWrite = QtWidgets.QPushButton(Form)
        self.btnWrite.setMinimumSize(QtCore.QSize(90, 0))
        self.btnWrite.setObjectName("btnWrite")
        self.horizontalLayout.addWidget(self.btnWrite)
        self.btnPause = QtWidgets.QPushButton(Form)
        self.btnPause.setMinimumSize(QtCore.QSize(90, 0))
        self.btnPause.setObjectName("btnPause")
        self.horizontalLayout.addWidget(self.btnPause)
        self.btnStop = QtWidgets.QPushButton(Form)
        self.btnStop.setMinimumSize(QtCore.QSize(90, 0))
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout.addWidget(self.btnStop)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lblTime = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTime.sizePolicy().hasHeightForWidth())
        self.lblTime.setSizePolicy(sizePolicy)
        self.lblTime.setMinimumSize(QtCore.QSize(80, 0))
        self.lblTime.setObjectName("lblTime")
        self.horizontalLayout.addWidget(self.lblTime)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblProcess = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblProcess.sizePolicy().hasHeightForWidth())
        self.lblProcess.setSizePolicy(sizePolicy)
        self.lblProcess.setObjectName("lblProcess")
        self.horizontalLayout_2.addWidget(self.lblProcess)
        self.lblCurrent = QtWidgets.QLabel(Form)
        self.lblCurrent.setObjectName("lblCurrent")
        self.horizontalLayout_2.addWidget(self.lblCurrent)
        spacerItem1 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lblHap = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHap.sizePolicy().hasHeightForWidth())
        self.lblHap.setSizePolicy(sizePolicy)
        self.lblHap.setObjectName("lblHap")
        self.horizontalLayout_2.addWidget(self.lblHap)
        self.progressBar = QtWidgets.QProgressBar(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QtCore.QSize(80, 0))
        self.progressBar.setMinimum(0)
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.Configuration = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Configuration.sizePolicy().hasHeightForWidth())
        self.Configuration.setSizePolicy(sizePolicy)
        self.Configuration.setAutoFillBackground(False)
        self.Configuration.setObjectName("Configuration")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Configuration)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lbl_config = QtWidgets.QLabel(self.Configuration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_config.sizePolicy().hasHeightForWidth())
        self.lbl_config.setSizePolicy(sizePolicy)
        self.lbl_config.setObjectName("lbl_config")
        self.verticalLayout_5.addWidget(self.lbl_config)
        self.tableConfig = QtWidgets.QTableWidget(self.Configuration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableConfig.sizePolicy().hasHeightForWidth())
        self.tableConfig.setSizePolicy(sizePolicy)
        self.tableConfig.setMinimumSize(QtCore.QSize(0, 50))
        self.tableConfig.setMaximumSize(QtCore.QSize(16777215, 250))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableConfig.setFont(font)
        self.tableConfig.setAutoFillBackground(False)
        self.tableConfig.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableConfig.setAlternatingRowColors(True)
        self.tableConfig.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableConfig.setShowGrid(True)
        self.tableConfig.setGridStyle(QtCore.Qt.SolidLine)
        self.tableConfig.setRowCount(1)
        self.tableConfig.setColumnCount(15)
        self.tableConfig.setObjectName("tableConfig")
        self.tableConfig.horizontalHeader().setCascadingSectionResizes(False)
        self.tableConfig.horizontalHeader().setDefaultSectionSize(100)
        self.tableConfig.horizontalHeader().setHighlightSections(True)
        self.tableConfig.horizontalHeader().setSortIndicatorShown(True)
        self.tableConfig.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout_5.addWidget(self.tableConfig)
        self.lbl_histo = QtWidgets.QLabel(self.Configuration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_histo.sizePolicy().hasHeightForWidth())
        self.lbl_histo.setSizePolicy(sizePolicy)
        self.lbl_histo.setObjectName("lbl_histo")
        self.verticalLayout_5.addWidget(self.lbl_histo)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")

        self.matplotlibWidget = MatplotlibWidget(self.Configuration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matplotlibWidget.sizePolicy().hasHeightForWidth())
        self.matplotlibWidget.setSizePolicy(sizePolicy)
        self.matplotlibWidget.setObjectName("matplotlibWidget")
        # self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.matplotlibWidget)
        # self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        # self.horizontalLayout_5.setObjectName("horizontalLayout_5")

        self.horizontalLayout_6.addWidget(self.matplotlibWidget)
        self.line_7 = QtWidgets.QFrame(self.Configuration)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_6.addWidget(self.line_7)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_6.setSpacing(10)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_5 = QtWidgets.QLabel(self.Configuration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 0, 1, 1, 1)
        self.comboPlotSettings = QtWidgets.QComboBox(self.Configuration)
        self.comboPlotSettings.setObjectName("comboPlotSettings")
        self.gridLayout_6.addWidget(self.comboPlotSettings, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem3, 2, 1, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Configuration, "")
        self.Operations = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Operations.sizePolicy().hasHeightForWidth())
        self.Operations.setSizePolicy(sizePolicy)
        self.Operations.setAutoFillBackground(False)
        self.Operations.setObjectName("Operations")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Operations)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lbl_flights = QtWidgets.QLabel(self.Operations)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_flights.sizePolicy().hasHeightForWidth())
        self.lbl_flights.setSizePolicy(sizePolicy)
        self.lbl_flights.setObjectName("lbl_flights")
        self.verticalLayout_7.addWidget(self.lbl_flights)
        self.tableFlights = QtWidgets.QTableWidget(self.Operations)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableFlights.sizePolicy().hasHeightForWidth())
        self.tableFlights.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableFlights.setFont(font)
        self.tableFlights.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableFlights.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableFlights.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableFlights.setAlternatingRowColors(True)
        self.tableFlights.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableFlights.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableFlights.setRowCount(200)
        self.tableFlights.setColumnCount(15)
        self.tableFlights.setObjectName("tableFlights")
        self.tableFlights.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout_7.addWidget(self.tableFlights)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Operations, "")
        self.Settings = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Settings.sizePolicy().hasHeightForWidth())
        self.Settings.setSizePolicy(sizePolicy)
        self.Settings.setObjectName("Settings")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Settings)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.line_3 = QtWidgets.QFrame(self.Settings)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 2, 1, 1)
        self.timeEdit = QtWidgets.QTimeEdit(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit.sizePolicy().hasHeightForWidth())
        self.timeEdit.setSizePolicy(sizePolicy)
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout.addWidget(self.timeEdit, 5, 1, 1, 1)
        self.lbl_start_time = QtWidgets.QLabel(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_start_time.sizePolicy().hasHeightForWidth())
        self.lbl_start_time.setSizePolicy(sizePolicy)
        self.lbl_start_time.setScaledContents(False)
        self.lbl_start_time.setObjectName("lbl_start_time")
        self.gridLayout.addWidget(self.lbl_start_time, 2, 1, 1, 1)
        self.calendarWidget_2 = QtWidgets.QCalendarWidget(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarWidget_2.sizePolicy().hasHeightForWidth())
        self.calendarWidget_2.setSizePolicy(sizePolicy)
        self.calendarWidget_2.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget_2.setObjectName("calendarWidget_2")
        self.gridLayout.addWidget(self.calendarWidget_2, 3, 2, 1, 1)
        self.lbl_end_time = QtWidgets.QLabel(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_end_time.sizePolicy().hasHeightForWidth())
        self.lbl_end_time.setSizePolicy(sizePolicy)
        self.lbl_end_time.setObjectName("lbl_end_time")
        self.gridLayout.addWidget(self.lbl_end_time, 2, 2, 1, 1)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarWidget.sizePolicy().hasHeightForWidth())
        self.calendarWidget.setSizePolicy(sizePolicy)
        self.calendarWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.calendarWidget.setGridVisible(False)
        self.calendarWidget.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout.addWidget(self.calendarWidget, 3, 1, 1, 1)
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit_2.sizePolicy().hasHeightForWidth())
        self.timeEdit_2.setSizePolicy(sizePolicy)
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.gridLayout.addWidget(self.timeEdit_2, 5, 2, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.Settings)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 3, 3, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.Settings)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.spinBoxRate = QtWidgets.QSpinBox(self.Settings)
        self.spinBoxRate.setProperty("value", 5)
        self.spinBoxRate.setObjectName("spinBoxRate")
        self.horizontalLayout_3.addWidget(self.spinBoxRate)
        self.btnSetRate = QtWidgets.QPushButton(self.Settings)
        self.btnSetRate.setObjectName("btnSetRate")
        self.horizontalLayout_3.addWidget(self.btnSetRate)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 7, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.Settings)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 1, 1, 1)
        self.checkBoxDelimit = QtWidgets.QCheckBox(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxDelimit.sizePolicy().hasHeightForWidth())
        self.checkBoxDelimit.setSizePolicy(sizePolicy)
        self.checkBoxDelimit.setObjectName("checkBoxDelimit")
        self.gridLayout.addWidget(self.checkBoxDelimit, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.Settings)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 4, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_5.setSpacing(10)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_4 = QtWidgets.QLabel(self.Settings)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.Settings)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_5.addItem(spacerItem5, 3, 1, 1, 1)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_2.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_2.setSizePolicy(sizePolicy)
        self.plainTextEdit_2.setMinimumSize(QtCore.QSize(0, 30))
        self.plainTextEdit_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.gridLayout_5.addWidget(self.plainTextEdit_2, 2, 1, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_5.addWidget(self.plainTextEdit, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 7, 1, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.Settings)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 6, 2, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.Settings)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 6, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Settings, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_6.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.btnRun, self.btnOpen)
        Form.setTabOrder(self.btnOpen, self.btnWrite)
        Form.setTabOrder(self.btnWrite, self.btnStop)
        Form.setTabOrder(self.btnStop, self.btnOpen)
        Form.setTabOrder(self.btnOpen, self.btnRun)
        Form.setTabOrder(self.btnRun, self.btnWrite)
        Form.setTabOrder(self.btnWrite, self.btnStop)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Runway Allocation"))
        self.btnOpen.setText(_translate("Form", "Select files"))
        self.btnRun.setText(_translate("Form", "Run"))
        self.btnWrite.setText(_translate("Form", "Write logs"))
        self.btnPause.setText(_translate("Form", "Pause"))
        self.btnStop.setText(_translate("Form", "Stop"))
        self.lblTime.setText(_translate("Form", "..."))
        self.lblProcess.setText(_translate("Form", "Process..."))
        self.lblCurrent.setText(_translate("Form", "..."))
        self.lblHap.setText(_translate("Form", "Ready..."))
        self.lbl_config.setText(_translate("Form", "Configuration table"))
        self.tableConfig.setSortingEnabled(True)
        self.lbl_histo.setText(_translate("Form", "Throughput histogram"))
        self.label_5.setText(_translate("Form", "Plot settings:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Configuration), _translate("Form", "Configuration"))
        self.lbl_flights.setText(_translate("Form", "Operations table"))
        self.tableFlights.setSortingEnabled(True)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Operations), _translate("Form", "Operations"))
        self.lbl_start_time.setText(_translate("Form", "Start date and time (UTC)"))
        self.lbl_end_time.setText(_translate("Form", "End date and time (UTC)"))
        self.label_2.setText(_translate("Form", "Refresh rate: "))
        self.spinBoxRate.setSuffix(_translate("Form", " (s)"))
        self.btnSetRate.setText(_translate("Form", "Set"))
        self.checkBoxDelimit.setText(_translate("Form", "delimited time range"))
        self.label.setText(_translate("Form", "..."))
        self.label_4.setText(_translate("Form", "TextLabel:"))
        self.label_3.setText(_translate("Form", "Out file name:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Settings), _translate("Form", "Settings"))

    def set_controller(self, controller2):
        self.controller = controller2


class MatplotlibWidget(QtWidgets.QWidget):  # TODO script this class in controller
    def __init__(self, parent=None):
        super(MatplotlibWidget, self).__init__(parent)

        self.figure = Figure(edgecolor='k')
        self.figure.subplots_adjust(left=0.05, right=0.95, top=0.85, bottom=0.15)
        self.figure.set_size_inches(7, 3)
        self.canvas = FigureCanvasQTAgg(self.figure)
        self.axes = self.figure.add_subplot(111)
        self.axes.set_title('Dep/Arr')

        self.scroll = QtWidgets.QScrollArea(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll.sizePolicy().hasHeightForWidth())
        self.scroll.setSizePolicy(sizePolicy)
        self.scroll.setWidget(self.canvas)

        self.layoutVertical = QtWidgets.QVBoxLayout(self)
        self.layoutVertical.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layoutVertical.setContentsMargins(0, 0, 0, 0)
        self.nav = NavigationToolbar(self.canvas, self)
        self.layoutVertical.addWidget(self.nav)
        self.layoutVertical.addWidget(self.scroll)

        # self.scroll.resize(self.layoutVertical.geometry().width(), self.layoutVertical.geometry().height())

        self.bins = [1]
        self.binsize = 15  # min
        self.max_y = self.binsize*1.2
        self.scroll_resize = False
        self.show_labels = False
        self.stacked = True
        self.reset_fig()

    def reset_fig(self):
        self.axes.clear()
        self.axes.grid(True)
        self.axes.set_title('Dep/Arr', loc='center')
        self.resize_fig()

    def resize_fig(self):
        dpi1 = self.figure.get_dpi()
        if self.scroll_resize and len(self.bins) >= 5 and len(self.bins)*50 >= self.scroll.width():
            self.figure.set_size_inches(len(self.bins)*50 / float(dpi1),
                                        (self.scroll.height()-20) / float(dpi1))
            self.canvas.resize(self.figure.get_figwidth() * float(dpi1), self.figure.get_figheight() * float(dpi1))
        else:
            self.figure.set_size_inches((self.scroll.width()) / float(dpi1),
                                        (self.scroll.height()-20) / float(dpi1))
            self.canvas.resize(self.figure.get_figwidth()*float(dpi1), self.figure.get_figheight()*float(dpi1))

    def update_figure(self, op_list, config_list):  # TODO legend
        self.reset_fig()
        # operation histogram
        last_time = op_list[0].op_timestamp - op_list[0].op_timestamp % (self.binsize * 60)
        dep = []
        arr = []
        for m, op in enumerate(op_list):
            delay = (last_time - op.op_timestamp)/60.0
            if op.LorT == 'T':
                dep.append(delay)
            elif op.LorT == 'L':
                arr.append(delay)
        self.bins = np.arange(0, arr[-1]/self.binsize + 1)*self.binsize
        if self.stacked:
            [n0, n1], bins2, patches = self.axes.hist([arr, dep], bins=self.bins, stacked=True, rwidth=0.9,
                                                  color=['#9CB380', '#5CC8FF'], label=['arr', 'dep'])
        else:
            [n0, n1], bins2, patches = self.axes.hist([arr, dep], bins=self.bins, histtype = 'bar', rwidth = 0.9,
                                       color = ['#9CB380', '#5CC8FF'], label = ['arr', 'dep'])

        # n0, bins2, patches = self.axes.hist(arr, bins=self.bins, stacked=True, color='#9CB380', rwidth=0.9, label='arr')
        # n1, bins2, patches = self.axes.hist(dep, bins=self.bins, stacked=True, color='#5CC8FF', rwidth=0.9, label='dep')
        self.axes.legend(loc=2)
        # self.max_y = max([x+y for x, y in zip(n[0], n[1])])
        if self.show_labels:
            for m1, count1 in enumerate(n0):
                self.axes.text(self.bins[m1] + self.binsize*0.25, count1+self.max_y*0.02, '{:.0f}'.format(count1))
            for m2, count2 in enumerate(n1):
                self.axes.text(self.bins[m2] + self.binsize*0.75, count2+self.max_y*0.02, '{:.0f}'.format(count2))

        # config changes vertical lines
        for m, config in enumerate(config_list):
            self.axes.plot([(last_time - config.from_epoch)/60.0]*2, [0, 0.85*self.max_y], 'b--', linewidth=1)
            self.axes.text((last_time - config.from_epoch)/60.0-self.binsize*0.2, self.max_y*0.9, config.config)

        # line of mean horizontal line (per day)
        avg = np.average(n1)
        # avg = np.average([x+y for x, y in zip(n0, n1)])
        self.axes.plot(self.bins, [avg] * len(self.bins), 'k--', linewidth=0.6)
        self.axes.text(0, self.max_y*1.05,
                       "Average throughput per bin: " + '{:.1f}'.format(avg) + "\nBin size is: " +
                       '{:d}'.format(self.binsize) + " min")

        # show plot
        self.axes.set_xticks(self.bins)
        self.axes.set_xlim([0, self.bins[-1]])
        self.axes.set_ylim([0, self.max_y])
        self.canvas.draw()


class Form(QtWidgets.QWidget):
    def __init__(self):
        QtWidgets.QWidget.__init__(self)
        self.resizeEvent = self.onRezise

    def closeEvent(self, QCloseEvent):
        QCloseEvent.ignore()
        self.ui.controller.close_application()

    def set_ui(self, ui):
        self.ui = ui

    def onRezise(self, event):
        self.ui.matplotlibWidget.resize_fig()


def run():
    import controller
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form = Form()
    ui = Ui_Form()
    ui.setupUi(form)
    ui.set_controller(controller.make_controller(ui))
    form.set_ui(ui)
    form.show()
    sys.exit(app.exec_())

